sonar.projectKey=lhotakr_RemesloStredoveku
sonar.organization=lhotakr

sonar.exclusions=third_party/**,vcpkg/**,vcpkg_installed/**,cmake-build-debug/**,out/**,repair_payload/**,.idea/**,.vs/**,/data/**,/vcpkg*/**