#pragma once

// Generated by build_skill_tree_assets.py. Pixel coordinates in the 2048x2048 atlas.
namespace SmithingSkillTreeAtlas {
inline constexpr int Width = 2048;
inline constexpr int Height = 2048;
struct Rect { int x, y, w, h; };

inline constexpr Rect nodes_active{4, 4, 360, 176};
inline constexpr Rect nodes_available{368, 4, 360, 176};
inline constexpr Rect nodes_completed{732, 4, 360, 176};
inline constexpr Rect nodes_locked_far{1096, 4, 360, 176};
inline constexpr Rect nodes_locked_near{1460, 4, 360, 176};
inline constexpr Rect nodes_secret{4, 184, 360, 176};
inline constexpr Rect nodes_selected{368, 184, 360, 176};
inline constexpr Rect overlays_fog_far{732, 184, 360, 176};
inline constexpr Rect overlays_fog_near{1096, 184, 360, 176};
inline constexpr Rect icons_apprentice{1460, 184, 72, 72};
inline constexpr Rect icons_axe{1536, 184, 72, 72};
inline constexpr Rect icons_bellows{1612, 184, 72, 72};
inline constexpr Rect icons_building_ironwork{1688, 184, 72, 72};
inline constexpr Rect icons_chisel{1764, 184, 72, 72};
inline constexpr Rect icons_defect_detection{1840, 184, 72, 72};
inline constexpr Rect icons_diagnostics{1916, 184, 72, 72};
inline constexpr Rect icons_farriery{4, 364, 72, 72};
inline constexpr Rect icons_forge_safety{80, 364, 72, 72};
inline constexpr Rect icons_forge_weld{156, 364, 72, 72};
inline constexpr Rect icons_fuel{232, 364, 72, 72};
inline constexpr Rect icons_grind{308, 364, 72, 72};
inline constexpr Rect icons_heat_color{384, 364, 72, 72};
inline constexpr Rect icons_heat_treatment{460, 364, 72, 72};
inline constexpr Rect icons_hoe{536, 364, 72, 72};
inline constexpr Rect icons_hook{612, 364, 72, 72};
inline constexpr Rect icons_horseshoe{688, 364, 72, 72};
inline constexpr Rect icons_innovator{764, 364, 72, 72};
inline constexpr Rect icons_journeyman{840, 364, 72, 72};
inline constexpr Rect icons_knife{916, 364, 72, 72};
inline constexpr Rect icons_master{992, 364, 72, 72};
inline constexpr Rect icons_material_estimate{1068, 364, 72, 72};
inline constexpr Rect icons_nail{1144, 364, 72, 72};
inline constexpr Rect icons_observer{1220, 364, 72, 72};
inline constexpr Rect icons_planning{1296, 364, 72, 72};
inline constexpr Rect icons_quench{1372, 364, 72, 72};
inline constexpr Rect icons_repair{1448, 364, 72, 72};
inline constexpr Rect icons_resources{1524, 364, 72, 72};
inline constexpr Rect icons_staple{1600, 364, 72, 72};
inline constexpr Rect icons_straighten{1676, 364, 72, 72};
inline constexpr Rect icons_teamwork{1752, 364, 72, 72};
inline constexpr Rect icons_temperature_control{1828, 364, 72, 72};
inline constexpr Rect icons_tongs{1904, 364, 72, 72};
inline constexpr Rect icons_toolmaking{4, 440, 72, 72};
inline constexpr Rect icons_tools{80, 440, 72, 72};
inline constexpr Rect icons_workshop_master{156, 440, 72, 72};
inline constexpr Rect badges_choice{232, 440, 48, 48};
inline constexpr Rect badges_complete{284, 440, 48, 48};
inline constexpr Rect badges_lock{336, 440, 48, 48};
inline constexpr Rect badges_question{388, 440, 48, 48};
inline constexpr Rect pins_active{440, 440, 32, 32};
inline constexpr Rect pins_available{476, 440, 32, 32};
inline constexpr Rect pins_completed{512, 440, 32, 32};
inline constexpr Rect pins_locked{548, 440, 32, 32};
inline constexpr Rect pins_secret{584, 440, 32, 32};
inline constexpr Rect progress_complete_fill{620, 440, 256, 18};
inline constexpr Rect progress_fill{880, 440, 256, 18};
inline constexpr Rect progress_track{1140, 440, 256, 18};

} // namespace SmithingSkillTreeAtlas
