#pragma once

// Generated by build_imgui_assets.py. Atlas coordinates use pixels.
namespace SmithingUiAtlas {
inline constexpr int Width = 2048;
inline constexpr int Height = 1024;
struct Rect { int x, y, w, h; };

inline constexpr Rect chrome_panel_iron{4, 4, 192, 192};
inline constexpr Rect chrome_panel_overlay{204, 4, 192, 192};
inline constexpr Rect chrome_panel_parchment{404, 4, 192, 192};
inline constexpr Rect chrome_panel_wood{604, 4, 192, 192};
inline constexpr Rect chrome_portrait_medallion{804, 4, 128, 128};
inline constexpr Rect indicators_focus_glow{940, 4, 128, 128};
inline constexpr Rect indicators_target_reticle{1076, 4, 128, 128};
inline constexpr Rect controls_tab_active{1212, 4, 112, 128};
inline constexpr Rect controls_tab_completed{1332, 4, 112, 128};
inline constexpr Rect controls_tab_hover{1452, 4, 112, 128};
inline constexpr Rect controls_tab_locked{1572, 4, 112, 128};
inline constexpr Rect controls_tab_normal{1692, 4, 112, 128};
inline constexpr Rect chrome_title_plaque{4, 204, 384, 112};
inline constexpr Rect controls_observation_damage{396, 204, 320, 84};
inline constexpr Rect controls_observation_neutral{724, 204, 320, 84};
inline constexpr Rect controls_observation_positive{1052, 204, 320, 84};
inline constexpr Rect controls_observation_warning{1380, 204, 320, 84};
inline constexpr Rect controls_button_disabled{1708, 204, 320, 64};
inline constexpr Rect controls_button_hover{4, 324, 320, 64};
inline constexpr Rect controls_button_normal{332, 324, 320, 64};
inline constexpr Rect controls_button_pressed{660, 324, 320, 64};
inline constexpr Rect icons_observations_accept{988, 324, 64, 64};
inline constexpr Rect icons_observations_axis{1060, 324, 64, 64};
inline constexpr Rect icons_observations_color{1132, 324, 64, 64};
inline constexpr Rect icons_observations_crack{1204, 324, 64, 64};
inline constexpr Rect icons_observations_edge{1276, 324, 64, 64};
inline constexpr Rect icons_observations_exit{1348, 324, 64, 64};
inline constexpr Rect icons_observations_fit{1420, 324, 64, 64};
inline constexpr Rect icons_observations_heat{1492, 324, 64, 64};
inline constexpr Rect icons_observations_impact{1564, 324, 64, 64};
inline constexpr Rect icons_observations_info{1636, 324, 64, 64};
inline constexpr Rect icons_observations_reflection{1708, 324, 64, 64};
inline constexpr Rect icons_observations_repair{1780, 324, 64, 64};
inline constexpr Rect icons_observations_shape{1852, 324, 64, 64};
inline constexpr Rect icons_observations_sound{1924, 324, 64, 64};
inline constexpr Rect icons_observations_sparks{4, 396, 64, 64};
inline constexpr Rect icons_observations_steam{76, 396, 64, 64};
inline constexpr Rect icons_observations_surface{148, 396, 64, 64};
inline constexpr Rect icons_observations_thickness{220, 396, 64, 64};
inline constexpr Rect icons_observations_vibration{292, 396, 64, 64};
inline constexpr Rect icons_observations_wood{364, 396, 64, 64};
inline constexpr Rect icons_stations_anvil{436, 396, 64, 64};
inline constexpr Rect icons_stations_forge{508, 396, 64, 64};
inline constexpr Rect icons_stations_grindstone{580, 396, 64, 64};
inline constexpr Rect icons_stations_quench{652, 396, 64, 64};
inline constexpr Rect icons_stations_testing{724, 396, 64, 64};
inline constexpr Rect icons_stations_workbench{796, 396, 64, 64};
inline constexpr Rect indicators_phase_active{868, 396, 64, 64};
inline constexpr Rect indicators_phase_completed{940, 396, 64, 64};
inline constexpr Rect indicators_phase_locked{1012, 396, 64, 64};
inline constexpr Rect indicators_phase_pending{1084, 396, 64, 64};
inline constexpr Rect indicators_phase_warning{1156, 396, 64, 64};
inline constexpr Rect controls_chip_active{1228, 396, 192, 48};
inline constexpr Rect controls_chip_damage{1428, 396, 192, 48};
inline constexpr Rect controls_chip_normal{1628, 396, 192, 48};
inline constexpr Rect controls_chip_warning{1828, 396, 192, 48};
inline constexpr Rect controls_keycap_normal{4, 468, 144, 48};
inline constexpr Rect controls_keycap_pressed{156, 468, 144, 48};
inline constexpr Rect indicators_status_damage{308, 468, 40, 40};
inline constexpr Rect indicators_status_neutral{356, 468, 40, 40};
inline constexpr Rect indicators_status_positive{404, 468, 40, 40};
inline constexpr Rect indicators_status_warning{452, 468, 40, 40};
inline constexpr Rect chrome_separator_horizontal{500, 468, 512, 16};

} // namespace SmithingUiAtlas
